-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.almacenes
(
    id_almacen serial NOT NULL,
    direccion character varying(50) COLLATE pg_catalog."default",
    id_provincia serial NOT NULL,
    f_apertura date,
    CONSTRAINT id_almacen PRIMARY KEY (id_almacen)
);

CREATE TABLE IF NOT EXISTS public.avala
(
    id_avalador serial NOT NULL,
    CONSTRAINT id_avalador PRIMARY KEY (id_avalador)
);

CREATE TABLE IF NOT EXISTS public.colecciones
(
    id_coleccion serial NOT NULL,
    volumen integer,
    CONSTRAINT colecciones_pkey PRIMARY KEY (id_coleccion)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    consecutivo serial NOT NULL,
    cantidad integer,
    id_pedido serial NOT NULL,
    isbn integer,
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id_pedido, consecutivo)
);

CREATE TABLE IF NOT EXISTS public.libros
(
    isbn serial NOT NULL,
    autor character varying(50) COLLATE pg_catalog."default",
    editorial character varying(50) COLLATE pg_catalog."default",
    dni character varying(50) COLLATE pg_catalog."default",
    titulo character varying(50) COLLATE pg_catalog."default",
    id_coleccion integer,
    CONSTRAINT isbn PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido serial NOT NULL,
    forma_envio character varying(50) COLLATE pg_catalog."default",
    forma_pago character varying(50) COLLATE pg_catalog."default",
    id_socio serial NOT NULL,
    isbn integer,
    CONSTRAINT id_pedido PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.poblaciones
(
    id_poblacion serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    id_provincia serial NOT NULL,
    habitantes integer,
    CONSTRAINT id_poblacion PRIMARY KEY (id_poblacion)
);

CREATE TABLE IF NOT EXISTS public.provincia
(
    id_provincia serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    extens integer,
    id_almacen serial NOT NULL,
    CONSTRAINT id_provincia PRIMARY KEY (id_provincia)
);

CREATE TABLE IF NOT EXISTS public.socio
(
    id_socio serial NOT NULL,
    telefono character varying(50) COLLATE pg_catalog."default",
    dni character varying(50) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    apellidos character varying(50) COLLATE pg_catalog."default",
    id_avalador serial NOT NULL,
    id_poblacion serial NOT NULL,
    CONSTRAINT id_socio PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public.stock
(
    id_almacen serial NOT NULL,
    cantidad integer,
    isbn integer
);

ALTER TABLE IF EXISTS public.almacenes
    ADD CONSTRAINT id_provincia FOREIGN KEY (id_provincia)
    REFERENCES public.provincia (id_provincia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT id_pedido FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.libros
    ADD CONSTRAINT id_coleccion FOREIGN KEY (id_coleccion)
    REFERENCES public.colecciones (id_coleccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT id_socio FOREIGN KEY (id_socio)
    REFERENCES public.socio (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT isbn FOREIGN KEY (isbn)
    REFERENCES public.libros (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.poblaciones
    ADD CONSTRAINT id_provincia FOREIGN KEY (id_provincia)
    REFERENCES public.provincia (id_provincia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provincia
    ADD CONSTRAINT id_almacen FOREIGN KEY (id_almacen)
    REFERENCES public.almacenes (id_almacen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT id_avalador FOREIGN KEY (id_avalador)
    REFERENCES public.avala (id_avalador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT id_poblacion FOREIGN KEY (id_poblacion)
    REFERENCES public.poblaciones (id_poblacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.socio
    ADD CONSTRAINT socio_id_avalador_fkey FOREIGN KEY (id_avalador)
    REFERENCES public.avala (id_avalador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stock
    ADD CONSTRAINT id_almacen FOREIGN KEY (id_almacen)
    REFERENCES public.almacenes (id_almacen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stock
    ADD CONSTRAINT isbn FOREIGN KEY (isbn)
    REFERENCES public.libros (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;