-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asunto
(
    n_expediente integer NOT NULL,
    estado character varying(50) COLLATE pg_catalog."default",
    f_inicio date,
    f_final date,
    CONSTRAINT asunto_pkey PRIMARY KEY (n_expediente)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    dni character varying COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    n_expediente integer,
    CONSTRAINT cliente_pkey PRIMARY KEY (dni),
    CONSTRAINT uq_n_expediente UNIQUE (n_expediente)
);

CREATE TABLE IF NOT EXISTS public.procurador
(
    dni integer NOT NULL,
    direccion character varying(50) COLLATE pg_catalog."default",
    nombre character varying(50) COLLATE pg_catalog."default",
    n_expediente integer,
    CONSTRAINT procurador_pkey PRIMARY KEY (dni)
);

ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_n_expediente_fkey FOREIGN KEY (n_expediente)
    REFERENCES public.asunto (n_expediente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uq_n_expediente
    ON public.cliente(n_expediente);


ALTER TABLE IF EXISTS public.procurador
    ADD CONSTRAINT procurador_n_expediente_fkey FOREIGN KEY (n_expediente)
    REFERENCES public.asunto (n_expediente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;